// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqiYhsjSOduK0M9bqYEWf_DAlJWLe2_U',
    appId: '1:675678647624:web:ee537543a4b708ced62f7d',
    messagingSenderId: '675678647624',
    projectId: 'smartwaterstation-6b248',
    authDomain: 'smartwaterstation-6b248.firebaseapp.com',
    databaseURL: 'https://smartwaterstation-6b248-default-rtdb.firebaseio.com',
    storageBucket: 'smartwaterstation-6b248.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPGSjNiNc2V6xlH1liVML44JnitFnfHg',
    appId: '1:675678647624:android:def659cd3572c620d62f7d',
    messagingSenderId: '675678647624',
    projectId: 'smartwaterstation-6b248',
    databaseURL: 'https://smartwaterstation-6b248-default-rtdb.firebaseio.com',
    storageBucket: 'smartwaterstation-6b248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_3TXSQ8Zc1d_bBlTuob4zr7QpwlYFD8',
    appId: '1:675678647624:ios:8fda394834ba3cbfd62f7d',
    messagingSenderId: '675678647624',
    projectId: 'smartwaterstation-6b248',
    databaseURL: 'https://smartwaterstation-6b248-default-rtdb.firebaseio.com',
    storageBucket: 'smartwaterstation-6b248.firebasestorage.app',
    iosBundleId: 'com.example.waterStationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLqiYhsjSOduK0M9bqYEWf_DAlJWLe2_U',
    appId: '1:675678647624:web:04738766e4397b95d62f7d',
    messagingSenderId: '675678647624',
    projectId: 'smartwaterstation-6b248',
    authDomain: 'smartwaterstation-6b248.firebaseapp.com',
    databaseURL: 'https://smartwaterstation-6b248-default-rtdb.firebaseio.com',
    storageBucket: 'smartwaterstation-6b248.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_3TXSQ8Zc1d_bBlTuob4zr7QpwlYFD8',
    appId: '1:675678647624:ios:8fda394834ba3cbfd62f7d',
    messagingSenderId: '675678647624',
    projectId: 'smartwaterstation-6b248',
    databaseURL: 'https://smartwaterstation-6b248-default-rtdb.firebaseio.com',
    storageBucket: 'smartwaterstation-6b248.firebasestorage.app',
    iosBundleId: 'com.example.waterStationApp',
  );

}